### ISSUE TITLE
Create HTML from Selection is not applying syntax highlighting

### ISSUE THREAD

**Issue by davidmles** [textmate/textmate.tmbundle#4]
When selecting some code, for example a method, and calling the "create HTML from selection" command, it generates a `pre` code without syntax highlighting.

Selecting nothing and calling the "create HTML from document" command does create code with syntax highlighting.

Is this intended behaviour?

I suppose it's intended to be inserted in an existing HTML document so the "create CSS from current theme" is used to generate styles that can be added to existing ones.

**Comment by sorbits** [comment]
Correct, using the command with a subset of the document is not intended to generate styles etc. since the intention is that with a selection, we’re presenting the result in a context that already have styles, unlike a full document, which we may want to present on its own (with TextMate 1.x this was a way to print a document with syntax highlighting).

**Comment by davidmles** [comment]
Thanks :)
